import type { JourneyContent } from "../types";

export const lohri: JourneyContent = {
  id: "lohri",
  path: "/lohri-baisakhi",
  name: "Lohṛī & Vaisākhī",
  festival: "Lohri & Baisakhi",
  native: "ਲੋਹੜੀ ਤੇ ਵਿਸਾਖੀ",
  lang: "pa",
  script: "gurmukhi",
  tagline: "from the winter fire to the golden wheat",
  greeting: "ਵਧਾਈਆਂ",
  pageTitle: "Lohṛī & Vaisākhī — from the winter fire to the golden wheat",
  description:
    "Scroll through Punjab's farming year: children singing for Lohri on a foggy January night, the bonfire and a baby's first Lohri, the wheat turning from green to gold, the Vaisakhi harvest and bhangra, the Khalsa at Anandpur Sahib in 1699, and the village mela.",
  share:
    "From the Lohri fire in the January fog to the golden wheat of Vaisakhi.",
  keywords: [
    "Lohri",
    "ਲੋਹੜੀ",
    "Vaisakhi",
    "Baisakhi",
    "ਵਿਸਾਖੀ",
    "Punjab",
    "Sunder mundriye",
    "Dulla Bhatti",
    "rewri",
    "gajak",
    "til gur",
    "first Lohri",
    "gidda",
    "boliyan",
    "bhangra",
    "dhol",
    "tumbi",
    "algoza",
    "rabi harvest",
    "Khalsa Sajna Divas",
    "Anandpur Sahib",
    "Panj Pyare",
    "Nishan Sahib",
    "nagar kirtan",
    "langar",
    "Vaisakhi mela",
  ],
  length: 1150,
  hero: [0, 0, 0.04, 0.065],
  chapters: [
    {
      tithi: "Lohri · the last night of Poh",
      title: "Sunder mundriye",
      native: "ਸੁੰਦਰ ਮੁੰਦਰੀਏ",
      body: "Fog on the mustard and the cane, and children going door to door for their Lohri. They sing 'Sunder mundriye', the old song of Dulla Bhatti, the outlaw who saved girls from being sold and married them off as his own daughters. Every house sends them on with rewri, gur and a few coins.",
      window: [0.07, 0.09, 0.15, 0.175],
      side: "right",
    },
    {
      tithi: "Lohri · 13 January, after dark",
      title: "The Lohri fire",
      native: "ਲੋਹੜੀ ਦੀ ਅੱਗ",
      body: "Logs and paathiyan, cakes of dried cow dung, piled in the courtyard and lit at dusk. The family walks round it, a parikrama, throwing in til and gur, rewri, gajak, popcorn and peanuts: an offering to Agni, and a prayer for the wheat still green in the fields. Supper is sarson da saag and makki di roti.",
      window: [0.185, 0.205, 0.27, 0.295],
      side: "left",
    },
    {
      tithi: "Lohri · a first one",
      title: "Pehli Lohri",
      native: "ਪਹਿਲੀ ਲੋਹੜੀ",
      body: "A house with a new bride, or a new baby, daughter or son, keeps its first Lohri big. The relatives come, the child is carried round the fire, and gur and rewri go out to the whole street. The women dance gidda in a ring, clapping, and throw boliyan at each other: quick teasing couplets, answered with a shout.",
      window: [0.305, 0.325, 0.39, 0.415],
      side: "right",
    },
    {
      tithi: "Magh, Phagun, Chet · the rabi season",
      title: "Kanak",
      native: "ਕਣਕ",
      body: "The wheat, kanak, sown after Diwali, grows all winter under fog and frost. By Magh the mustard beside it is a sheet of yellow flower; by Chet the ears are heavy, and the whole plain of Punjab turns, field by field, from green to gold.",
      window: [0.425, 0.445, 0.51, 0.535],
      side: "left",
    },
    {
      tithi: "1 Vaisakh · 13 or 14 April",
      title: "Vaisakhi",
      native: "ਵਿਸਾਖੀ",
      body: "The first of Vaisakh, the solar new year, and the wheat is ready. Out come the daatris, the sickles, for the vaadhi, the reaping, and the sheaves are tied and stacked. Then the dhol starts, and the farmers dance bhangra in the stubble: arms up, shoulders shaking, a 'hoy!' at the top of every phrase.",
      window: [0.545, 0.565, 0.63, 0.655],
      side: "right",
    },
    {
      tithi: "Vaisakhi 1699 · Anandpur Sahib",
      title: "Khalsa Sajna",
      native: "ਖ਼ਾਲਸਾ ਸਾਜਨਾ",
      body: "On Vaisakhi in 1699, at Anandpur Sahib, Guru Gobind Singh Ji asked who would give his head. Five rose, one by one, from across India. He gave them amrit stirred with a khanda, the Panj Pyare, the first of the Khalsa, and then took it from them himself. Now the Nishan Sahib gets a fresh saffron cloth, the Panj Pyare lead the nagar kirtan, and langar feeds all who come.",
      window: [0.665, 0.685, 0.75, 0.775],
      side: "left",
    },
    {
      tithi: "Vaisakhi · the afternoon",
      title: "The mela",
      native: "ਵਿਸਾਖੀ ਦਾ ਮੇਲਾ",
      body: "Then the mela: a wooden jhoola turning, jalebis frying in a great kadhai, glass bangles and silk parandis on the stalls, circle kabaddi in the dust, and the dhol still going as the sun goes down over the cut fields.",
      window: [0.785, 0.805, 0.86, 0.885],
      side: "right",
    },
  ],
  finale: {
    native: "ਵਿਸਾਖੀ ਦੀਆਂ ਲੱਖ ਲੱਖ ਵਧਾਈਆਂ",
    english: "lakhs of good wishes, and a golden year",
    window: [0.905, 0.925, 0.975, 0.998],
  },
  hints: {
    scroll: "scroll into the fog",
    touch: [
      {
        text: "touch the fire to throw rewri and popcorn",
        window: [0.2, 0.215, 0.4, 0.415],
      },
      {
        text: "drag across the wheat to cut it",
        window: [0.56, 0.575, 0.64, 0.655],
      },
      { text: "touch to play the dhol", window: [0.8, 0.815, 0.87, 0.885] },
    ],
  },
  verse: {
    lines: [
      "ਵੈਸਾਖੁ ਭਲਾ ਸਾਖਾ ਵੇਸ ਕਰੇ ॥",
      "ਧਨ ਦੇਖੈ ਹਰਿ ਦੁਆਰਿ ਆਵਹੁ ਦਇਆ ਕਰੇ ॥",
      "ਨਾਨਕ ਵੈਸਾਖੀਂ ਪ੍ਰਭੁ ਪਾਵੈ ਸੁਰਤਿ ਸਬਦਿ ਮਨੁ ਮਾਨਾ ॥",
    ],
    lang: "pa",
    script: "gurmukhi",
    english:
      "Vaisakh is lovely: the branches put on their new leaves. The bride watches the door for her Lord: come, in Your mercy. … Nanak: in Vaisakh the Lord is found, when the mind is steeped in the Word.",
    source:
      "Guru Nanak Dev Ji, Bārah Māhā, Rāg Tukhārī · Sri Guru Granth Sahib Ji, Ang 1108",
  },
  card: { native: "ਲੱਖ ਲੱਖ ਵਧਾਈਆਂ", english: "Happy Lohri & Vaisakhi" },
  returnLink: "back to the Lohri fire",
  soundLabel:
    "dhol, tumbi, algoza, chimta, harmonium and nagara, with handclaps and calls",
  about: {
    name: "Lohri and Vaisakhi",
    alternateName: [
      "Lohri",
      "ਲੋਹੜੀ",
      "Vaisakhi",
      "Baisakhi",
      "ਵਿਸਾਖੀ",
      "Khalsa Sajna Divas",
    ],
    sameAs: "https://en.wikipedia.org/wiki/Vaisakhi",
  },
  ink: "#07060a",
};
