import type { JourneyContent } from "../types";

export const ganesh: JourneyContent = {
  id: "ganesh",
  path: "/ganesh-chaturthi",
  name: "Ganeshotsav",
  festival: "Ganesh Chaturthi",
  native: "गणेशोत्सव",
  lang: "mr",
  tagline: "bappa comes home",
  greeting: "गणपती बाप्पा मोरया",
  pageTitle: "Ganeshotsav — Bappa comes home",
  description:
    "Scroll through Ganesh Chaturthi as Maharashtra keeps it: a murti shaped from shadu clay and given its eyes, brought home to the dhol-tasha, the aarti before twenty-one modaks, ten days of pandals, and the long walk to the sea at Girgaon Chowpatty.",
  share: "From a lump of clay in the murtikar's workshop to the sea at Chowpatty: Ganpati Bappa Morya.",
  keywords: [
    "Ganesh Chaturthi",
    "Ganeshotsav",
    "गणेशोत्सव",
    "Ganpati Bappa Morya",
    "गणपती बाप्पा मोरया",
    "Vinayaka Chaturthi",
    "Bhadrapada Shukla Chaturthi",
    "Ganpati murti",
    "shadu clay",
    "Pen",
    "Lalbaug",
    "Lalbaugcha Raja",
    "aagman",
    "dhol-tasha pathak",
    "pranapratishtha",
    "Sukhakarta Dukhaharta",
    "ukadiche modak",
    "durva",
    "Anant Chaturdashi",
    "visarjan",
    "Girgaon Chowpatty",
    "Mumbai",
    "Pune",
  ],
  length: 1100,
  hero: [0, 0, 0.04, 0.07],
  chapters: [
    {
      tithi: "Bhadrapada · the weeks before",
      title: "The murti",
      native: "मूर्ती",
      body: "In the workshops of Pen and Lalbaug he is shaped by hand from grey shadu clay, left to dry, then painted. The eyes are painted last of all, and a cloth goes over him for the road home.",
      window: [0.08, 0.1, 0.17, 0.2],
      side: "right",
    },
    {
      tithi: "Shukla Chaturthi · the arrival",
      title: "Aagman",
      native: "आगमन",
      body: "He comes home through the streets behind a dhol-tasha pathak: the big dhols, the rattle of the tashas, the saffron dhwaj swinging over them, gulal in the air and everyone calling Ganpati Bappa Morya!",
      window: [0.21, 0.23, 0.3, 0.33],
      side: "left",
    },
    {
      tithi: "Chaturthi · pranapratishtha",
      title: "Aarti",
      native: "आरती",
      body: "The cloth comes off and, with mantras, life is called into the murti. Red jaswand, blades of durva, twenty-one ukadiche modak, then the aarti to cymbals and clapping: Sukhakarta Dukhaharta, bringer of joy, taker of sorrow.",
      window: [0.34, 0.36, 0.43, 0.46],
      side: "right",
    },
    {
      tithi: "Chaturthi to Chaturdashi",
      title: "Ten days",
      native: "दहा दिवस",
      body: "Every lane has its pandal and the city stays up to see them all. Children hear how Kartikeya raced round the world on his peacock, while Ganesha walked round Shiva and Parvati, his whole world, and won.",
      window: [0.47, 0.49, 0.57, 0.6],
      side: "left",
    },
    {
      tithi: "Anant Chaturdashi",
      title: "Miravaṇūk",
      native: "मिरवणूक",
      body: "On the fourteenth day the city walks him to the sea. Murtis taller than houses ride on trucks, the pathaks play at full force, the gulal hangs so thick the lights turn pink, and it goes on all night.",
      window: [0.61, 0.63, 0.7, 0.73],
      side: "right",
    },
    {
      tithi: "Anant Chaturdashi · Girgaon Chowpatty",
      title: "Visarjan",
      native: "विसर्जन",
      body: "One last aarti at the water's edge. Then he is carried out into the sea and let go, and the waves bring back only his flowers. Ganpati Bappa Morya, pudhchya varshi lavkar ya.",
      window: [0.74, 0.76, 0.83, 0.86],
      side: "left",
    },
  ],
  finale: { native: "गणपती\u00a0बाप्पा\u00a0मोरया, पुढच्या\u00a0वर्षी\u00a0लवकर\u00a0या", english: "come back soon next year", window: [0.9, 0.92, 0.975, 0.998] },
  hints: {
    scroll: "scroll to bring Bappa home",
    touch: [
      { text: "touch to throw gulal", window: [0.23, 0.25, 0.31, 0.33] },
      { text: "move to wave the aarti", window: [0.37, 0.39, 0.44, 0.46] },
      { text: "touch the crowd to throw gulal", window: [0.63, 0.65, 0.71, 0.73] },
      { text: "touch the sea to offer a flower", window: [0.8, 0.82, 0.96, 0.99] },
    ],
  },
  verse: {
    lines: ["वक्रतुण्ड महाकाय सूर्यकोटि समप्रभ ।", "निर्विघ्नं कुरु मे देव सर्वकार्येषु सर्वदा ॥"],
    lang: "sa",
    english: "O curved trunk, great of body, bright as a million suns: my lord, keep every work of mine free of obstacles, always.",
    source: "Vakratuṇḍa śloka, said before beginning anything",
  },
  card: { native: "गणेश चतुर्थीच्या हार्दिक शुभेच्छा", english: "Happy Ganesh Chaturthi" },
  returnLink: "back to the workshop",
  soundLabel: "dhol-tasha, jhanj, aarti bells and clapping, bansuri and the sea",
  about: {
    name: "Ganesh Chaturthi",
    alternateName: ["Ganeshotsav", "गणेशोत्सव", "Vinayaka Chaturthi", "गणेश चतुर्थी"],
    sameAs: "https://en.wikipedia.org/wiki/Ganesh_Chaturthi",
  },
  ink: "#080406",
};
