import type { JourneyContent } from "../types";

export const bihu: JourneyContent = {
  id: "bihu",
  path: "/bihu",
  name: "Rongālī Bihu",
  festival: "Bihu",
  native: "ৰঙালী বিহু",
  lang: "as",
  script: "bangla",
  tagline: "spring, and the new year, in Assam",
  greeting: "শুভ বিহু",
  pageTitle: "Rongālī Bihu — spring, and the new year, in Assam",
  description:
    "Scroll through Rongali Bihu in the Brahmaputra valley: the kopou orchid in flower at the end of Chot, the cattle bathed at the pond on Goru Bihu, a gamosa for every elder on the new year, the husori singing from house to house, and the Bihu dance under the trees until the fireflies come out.",
  share: "From the cattle at the pond at dawn to the Bihu dance under the trees.",
  keywords: [
    "Bihu",
    "Rongali Bihu",
    "Bohag Bihu",
    "ৰঙালী বিহু",
    "Assamese New Year",
    "Goru Bihu",
    "Manuh Bihu",
    "Husori",
    "Bihu dance",
    "Mukoli Bihu",
    "gamosa",
    "kopou phool",
    "namghar",
    "mekhela chador",
    "muga silk",
    "dhol",
    "pepa",
    "gogona",
    "toka",
    "xorai",
    "pitha",
    "Assam",
    "Brahmaputra",
  ],
  length: 1150,
  hero: [0, 0, 0.04, 0.07],
  chapters: [
    {
      tithi: "Chot · the last days of the year",
      title: "Kopou Phool",
      native: "কপৌ ফুল",
      body: "Chot is the last month of the Assamese year. In the Brahmaputra valley the tea bushes flush green, the bamboo creaks in the wind, the kuli, the koel, calls all day, and the kopou orchid hangs its pink tails from the trees. In the yard of the namghar, the thatched prayer hall, the young have begun the first songs.",
      window: [0.08, 0.1, 0.17, 0.2],
      side: "right",
    },
    {
      tithi: "Goru Bihu · the last day of Chot",
      title: "Goru Bihu",
      native: "গৰু বিহু",
      body: "At first light the cattle that pull the plough are led to the pond. They are rubbed with maah-halodhi, black gram and turmeric ground to a paste, bathed, and switched gently with dighloti and makhioti leaves to keep the flies off, while the boys sing: “lao kha, bengena kha, bosore bosore barhi ja”, eat gourd, eat brinjal, grow bigger every year. By evening they have new ropes.",
      window: [0.22, 0.24, 0.31, 0.34],
      side: "left",
    },
    {
      tithi: "Manuh Bihu · 1 Bohag, the new year",
      title: "Manuh Bihu",
      native: "মানুহ বিহু",
      body: "The people’s Bihu. A bath, new clothes, and then to the elders, to touch their feet and give each a gamosa, the white cloth with its red border, woven on the loom at home. They bless you for the year. Then pitha and laru: til pitha rolled round sesame and jaggery, ghila pitha fried in oil, and doi-chira, curd poured over flattened rice.",
      window: [0.36, 0.38, 0.45, 0.48],
      side: "right",
    },
    {
      tithi: "Bohag · house to house",
      title: "Husori",
      native: "হুচৰি",
      body: "Bands of men go from courtyard to courtyard, first to the namghar and then to every house, with dhol, pepa and taal. They sing and dance in a ring, then stand to bless the house for the year ahead. The family brings tamul-paan, areca nut and betel leaf, on a xorai, the bell-metal tray on its stand, and a gamosa for each of them.",
      window: [0.5, 0.52, 0.59, 0.62],
      side: "left",
    },
    {
      tithi: "Bohag · the afternoon",
      title: "Bihu Naach",
      native: "বিহু নাচ",
      body: "Under the trees the women dance in muga silk mekhela chador, gold with red borders, kopou flowers in their hair: the hips sway, the hands turn, the feet hardly leave the ground. The men play for them in dhoti and gamosa, the dhol galloping, the pepa, a buffalo-horn pipe, crying out over it all, the gogona twanging, the toka clacking. The songs are bihugeet, of spring and love.",
      window: [0.64, 0.66, 0.75, 0.78],
      side: "right",
    },
    {
      tithi: "Bohag · the night",
      title: "Mukoli Bihu",
      native: "মুকলি বিহু",
      body: "Bihu in the open. After dark it moves out into the fields, and the drums go on under a half moon while jonaki, fireflies, rise out of the grass. There are seven Bihus in all: Kutum Bihu for visiting kin, Mela Bihu for the fairs, and at the end Sera Bihu, to say goodbye until next Bohag.",
      window: [0.8, 0.82, 0.88, 0.905],
      side: "left",
    },
  ],
  finale: { native: "ৰঙালী বিহুৰ শুভেচ্ছা", english: "a happy Bihu, and a good new year", window: [0.92, 0.94, 0.978, 0.998] },
  hints: {
    scroll: "scroll into the spring",
    touch: [
      { text: "touch the tree for kopou flowers", window: [0.1, 0.12, 0.18, 0.2] },
      { text: "touch a cow to wash it", window: [0.245, 0.265, 0.32, 0.34] },
      { text: "touch to give the husori a gamosa", window: [0.52, 0.54, 0.6, 0.62] },
      { text: "touch to strike the dhol", window: [0.665, 0.685, 0.76, 0.78] },
    ],
  },
  verse: {
    lines: ["প্ৰথমে প্ৰণামো ব্ৰহ্মৰূপী সনাতন ।", "সৰ্ব্ব অৱতাৰৰ কাৰণ নাৰায়ণ ॥"],
    lang: "as",
    script: "bangla",
    english: "First I bow to the Eternal, who is Brahman: Narayana, from whom every avatar comes.",
    source: "Srimanta Sankardev · the opening verse of the Kīrtan Ghoxā, sung in every namghar",
  },
  card: { native: "ৰঙালী বিহুৰ শুভেচ্ছা", english: "Happy Rongali Bihu" },
  returnLink: "back to the kopou flowers",
  soundLabel: "Bihu dhol, pepa, gogona, toka, taal, baanhi, the koel and the pond",
  about: {
    name: "Bihu",
    alternateName: ["Rongali Bihu", "Bohag Bihu", "ৰঙালী বিহু", "Assamese New Year"],
    sameAs: "https://en.wikipedia.org/wiki/Bohag_Bihu",
  },
  ink: "#050806",
};
