import type { JourneyContent } from "../types";

export const chhath: JourneyContent = {
  id: "chhath",
  path: "/chhath",
  name: "Chhath",
  festival: "Chhath Puja",
  native: "छठ पूजा",
  lang: "bho",
  tagline: "the river at dusk and dawn",
  greeting: "जय छठी मइया",
  pageTitle: "Chhath — the river at dusk and dawn",
  description:
    "Scroll through the four days of Chhath by a river in Bihar: the bath and kaddu-bhaat of Nahay Khay, the kheer of Kharna, thekua and the soop, and the vratis waist deep in the water for the setting sun and the rising one.",
  share: "Four days by the river, from the setting sun to the rising one.",
  keywords: [
    "Chhath",
    "Chhath Puja",
    "छठ पूजा",
    "Chhathi Maiya",
    "Surya",
    "Nahay Khay",
    "Kharna",
    "Thekua",
    "soop",
    "daura",
    "Sandhya Arghya",
    "Usha Arghya",
    "Kosi Bharai",
    "ghat",
    "Bihar",
    "Bhojpuri",
  ],
  length: 1100,
  hero: [0, 0, 0.04, 0.07],
  chapters: [
    {
      tithi: "Nahay Khay · Kartik Shukla Chaturthi",
      title: "Nahay Khay",
      native: "नहाय-खाय",
      body: "At first light the vrati bathes in the river and carries its water home. The house is washed, and she eats once, cooked on a clay chulha over mango wood: kaddu-bhaat, of lauki, chana dal and rice, with rock salt.",
      window: [0.08, 0.1, 0.17, 0.2],
      side: "left",
    },
    {
      tithi: "Kharna · Panchami",
      title: "Kharna",
      native: "खरना",
      body: "A day without food or water, broken after dark with rasiya, rice cooked in jaggery, and roti, offered first and then shared. From here she keeps the nirjala fast: thirty-six hours without a sip of water.",
      window: [0.21, 0.23, 0.3, 0.33],
      side: "right",
    },
    {
      tithi: "Shashthi · the morning",
      title: "Thekua and the soop",
      native: "ठेकुआ",
      body: "Wheat, jaggery and ghee pressed in a wooden mould and fried. The bamboo soop is filled with sugarcane, coconut, bananas, gagal, singhara, thekua and a lamp, and the men carry the dauras to the ghat on their heads, the women singing behind: “kaanch hi baans ke bahangiya”.",
      window: [0.34, 0.36, 0.43, 0.46],
      side: "left",
    },
    {
      tithi: "Shashthi · dusk",
      title: "Sandhya Arghya",
      native: "संध्या अर्घ्य",
      body: "Waist deep in the river and facing the sun as it goes down, she holds up the soop, and milk and water are poured over it for Surya. Few festivals honour the setting sun; Chhath honours it first.",
      window: [0.47, 0.49, 0.57, 0.6],
      side: "right",
    },
    {
      tithi: "Shashthi · the night",
      title: "Kosi Bharai",
      native: "कोसी भराई",
      body: "Where a wish has come true, sugarcane is tied into a canopy over a clay elephant, a kalash and lamps, at home and again at the ghat. The women sit up with it all night, singing to Chhathi Maiya.",
      window: [0.61, 0.63, 0.7, 0.73],
      side: "left",
    },
    {
      tithi: "Saptami · dawn",
      title: "Usha Arghya",
      native: "उषा अर्घ्य",
      body: "Back in the cold water before first light, waiting. When Surya shows over the far bank the last arghya is given, “uga ho Suruj Dev”, and the fast is broken with prasad and shared with everyone on the ghat.",
      window: [0.74, 0.76, 0.83, 0.86],
      side: "left",
    },
  ],
  finale: { native: "जय छठी मइया", english: "for Chhathi Maiya, and the sun", window: [0.9, 0.92, 0.975, 0.998] },
  hints: {
    scroll: "scroll down to the river",
    touch: [
      { text: "touch the river to offer arghya", window: [0.5, 0.52, 0.58, 0.6] },
      { text: "touch the river to set a lamp afloat", window: [0.645, 0.665, 0.74, 0.76] },
      { text: "touch the water as the sun comes up", window: [0.78, 0.8, 0.87, 0.89] },
    ],
  },
  verse: {
    lines: ["तत्सवितुर्वरेण्यं", "भर्गो देवस्य धीमहि ।", "धियो यो नः प्रचोदयात् ॥"],
    lang: "sa",
    english: "We meditate on the glorious light of Savitṛ, the sun; may it light our minds.",
    source: "Ṛgveda 3.62.10 · the Gāyatrī",
  },
  card: { native: "छठ पूजा की शुभकामनाएँ", english: "Happy Chhath Puja" },
  returnLink: "back to the river",
  soundLabel: "bansuri, tanpura, dholak, manjira, the shankh and the river",
  about: {
    name: "Chhath",
    alternateName: ["Chhath Puja", "छठ पूजा", "Surya Shashthi", "Dala Chhath"],
    sameAs: "https://en.wikipedia.org/wiki/Chhath",
  },
  ink: "#07050c",
};
