import type { JourneyContent } from "../types";

export const janmashtami: JourneyContent = {
  id: "janmashtami",
  path: "/janmashtami",
  name: "Janmāṣṭamī",
  festival: "Krishna Janmashtami",
  native: "जन्माष्टमी",
  lang: "hi",
  script: "deva",
  tagline: "the night he was born",
  greeting: "जय श्री कृष्ण",
  pageTitle: "Janmāṣṭamī — the night he was born",
  description:
    "Scroll through the night Krishna was born: Kamsa's prison in the monsoon storm, the midnight light, Vasudeva carrying the child across the flooded Yamuna under Sheshnaag's hoods, dawn in Gokul, the midnight jhula in Vrindavan today, and the Dahi Handi in the streets of Maharashtra.",
  share: "From Kamsa's prison at midnight, across the Yamuna in flood, to the pot of butter hung high over the street.",
  keywords: [
    "Janmashtami",
    "Krishna Janmashtami",
    "जन्माष्टमी",
    "Gokulashtami",
    "Krishnashtami",
    "Bhadrapada Krishna Ashtami",
    "Rohini nakshatra",
    "Mathura",
    "Kamsa",
    "Devaki",
    "Vasudeva",
    "Yamuna",
    "Sheshnaag",
    "Gokul",
    "Nand baba",
    "Yashoda",
    "Nandotsav",
    "Vrindavan",
    "Laddu Gopal",
    "jhula",
    "chhappan bhog",
    "Dahi Handi",
    "Gopalkala",
    "govinda pathak",
    "Makhan chor",
    "bansuri",
  ],
  length: 1200,
  hero: [0, 0, 0.03, 0.055],
  chapters: [
    {
      tithi: "Mathura · Bhadrapada Krishna Ashtami",
      title: "Kamsa's prison",
      native: "कंस का कारागार",
      body: "A voice from the sky told Kamsa, king of Mathura, that his sister Devaki's eighth child would kill him. So he chained her and her husband Vasudeva in his prison and took each baby as it was born. Six he killed; the seventh, Balarama, was carried away in secret to Rohini's womb. On the eighth night of the waning moon, in the monsoon rain, she was ready to give birth again.",
      window: [0.06, 0.075, 0.13, 0.155],
      side: "left",
    },
    {
      tithi: "Ashtami · midnight, under Rohini",
      title: "The eighth child",
      native: "आधी रात",
      body: "At midnight, with the half moon of Ashtami rising behind the clouds, Krishna was born, and light filled the cell. The chains fell open, the guards fell asleep where they stood, and the doors swung open by themselves. Vasudeva laid the child in a basket.",
      window: [0.165, 0.18, 0.25, 0.275],
      side: "right",
    },
    {
      tithi: "The same night · the river in flood",
      title: "Crossing the Yamuna",
      native: "यमुना पार",
      body: "He carried the basket on his head out into the storm and into the Yamuna. The river rose and rose until it touched the child's feet, and then it fell back and let them through. Behind them Sheshnaag, the serpent Vishnu rests on, rose from the water and spread his hoods over the basket against the rain.",
      window: [0.285, 0.3, 0.4, 0.425],
      side: "left",
    },
    {
      tithi: "Gokul · dawn, Nandotsav",
      title: "Joy in Nand's house",
      native: "गोकुल",
      body: "In Gokul, Vasudeva laid the boy beside the sleeping Yashoda and carried her newborn daughter back to the prison. At dawn the cowherds' village woke to a son in Nand baba's house. Nand gave away cows, curd and turmeric were thrown in the lanes, and they sang what Braj still sings: “नंद के आनंद भयो, जय कन्हैया लाल की”.",
      window: [0.435, 0.45, 0.52, 0.545],
      side: "right",
    },
    {
      tithi: "Vrindavan · today, at midnight",
      title: "The jhula",
      native: "वृंदावन",
      body: "Devotees fast all day, many without grain or water, and the temples of Mathura and Vrindavan stay open into the night. At midnight the conch is blown and the curtain drawn back. Laddu Gopal, the baby Krishna, is bathed in panchamrit, dressed and set in a jhula, a swing heaped with flowers, before the chhappan bhog of fifty-six dishes. The fast is broken only after the aarti.",
      window: [0.555, 0.57, 0.64, 0.665],
      side: "left",
    },
    {
      tithi: "Gopalkala · the next day, Maharashtra",
      title: "Dahi Handi",
      native: "दही हंडी",
      body: "An earthen pot of curd and butter is hung high over the street, and a govinda pathak climbs for it: a human pyramid, tier on shoulders on tier, while the balconies throw water down on them. The smallest climbs last and breaks the pot, as Makhan chor, the butter thief, once reached the pots Yashoda hung out of his reach. “गोविंदा आला रे!”",
      window: [0.675, 0.69, 0.8, 0.825],
      side: "right",
    },
    {
      tithi: "Braj · dawn by the Yamuna",
      title: "Bansuri",
      native: "बाँसुरी",
      body: "In Braj he is remembered less as a king than as a cowherd boy: Gopal, with a bamboo flute and a peacock feather in his hair, taking the cows to graze under the kadamba trees by the Yamuna. After the storm, the river is calm again.",
      window: [0.835, 0.85, 0.9, 0.925],
      side: "left",
    },
  ],
  finale: { native: "नंद के आनंद भयो, जय कन्हैया लाल की", english: "joy in Nand's house: hail Kanhaiya", window: [0.935, 0.95, 0.985, 0.999] },
  hints: {
    scroll: "scroll into the storm",
    touch: [
      { text: "touch the sky for lightning", window: [0.065, 0.085, 0.4, 0.425] },
      { text: "touch the jhula to swing it", window: [0.575, 0.59, 0.645, 0.665] },
      { text: "tap to add a govinda, then tap the handi", window: [0.695, 0.71, 0.79, 0.81] },
    ],
  },
  verse: {
    lines: [
      "यदा यदा हि धर्मस्य ग्लानिर्भवति भारत ।",
      "अभ्युत्थानमधर्मस्य तदात्मानं सृजाम्यहम् ॥",
      "परित्राणाय साधूनां विनाशाय च दुष्कृताम् ।",
      "धर्मसंस्थापनार्थाय सम्भवामि युगे युगे ॥",
    ],
    lang: "sa",
    english:
      "Whenever dharma fails, O Bhārata, and adharma rises, I bring myself forth. To shelter the good, to end the wicked, and to set dharma firm again, I am born, age after age.",
    source: "Bhagavad Gītā 4.7–8",
  },
  card: { native: "जन्माष्टमी की शुभकामनाएँ", english: "Happy Janmashtami" },
  returnLink: "back to the storm",
  soundLabel: "bansuri, tanpura, temple bells and the shankh, pakhawaj, dholak and manjira, a dhol-tasha band, and the monsoon storm",
  about: {
    name: "Krishna Janmashtami",
    alternateName: ["Janmashtami", "जन्माष्टमी", "Gokulashtami", "Krishnashtami", "Srikrishna Jayanti"],
    sameAs: "https://en.wikipedia.org/wiki/Krishna_Janmashtami",
  },
  ink: "#04060c",
};
