import type { JourneyContent } from "../types";

export const pongal: JourneyContent = {
  id: "pongal",
  path: "/pongal",
  name: "Poṅgal",
  festival: "Pongal",
  native: "பொங்கல்",
  lang: "ta",
  script: "tamil",
  tagline: "when the pot boils over",
  greeting: "இனிய பொங்கல்",
  pageTitle: "Poṅgal — when the pot boils over",
  description:
    "Scroll through the four days of Pongal in a Tamil village: the Bhogi fire before dawn, a kolam looped in rice flour at the door, the new clay pot boiling over for Surya, the cattle painted and belled for Mattu Pongal, and a day out for Kaanum Pongal.",
  share:
    "Four days of the Tamil harvest, from the Bhogi fire to the pot boiling over.",
  keywords: [
    "Pongal",
    "Thai Pongal",
    "பொங்கல்",
    "தைப்பொங்கல்",
    "Bhogi",
    "Kolam",
    "Sikku kolam",
    "Pulli kolam",
    "Pongalo Pongal",
    "Surya",
    "Mattu Pongal",
    "Kaanum Pongal",
    "Kanu Pidi",
    "Jallikattu",
    "Thai",
    "Margazhi",
    "Nadaswaram",
    "Tamil Nadu",
    "harvest festival",
  ],
  length: 1150,
  hero: [0, 0, 0.04, 0.07],
  chapters: [
    {
      tithi: "The last day of Margazhi · before dawn",
      title: "Bhogi",
      native: "போகி",
      body: "The old mats, a broken winnowing basket and the worn-out broom go on a fire in the street: pazhaiyana kazhidhalum, pudhiyana pugudhalum, the old goes out and the new comes in. Children beat the little bhogi melam round it, and a kaappu of neem, yellow avaram and white poolai flowers is tied at the eaves of the freshly whitewashed house.",
      window: [0.08, 0.1, 0.17, 0.2],
      side: "left",
    },
    {
      tithi: "Thai 1 · first light",
      title: "Kolam",
      native: "கோலம்",
      body: "She sweeps the threshold, washes it with water and cow dung, and sets out the pulli, a grid of dots. Then one line of rice flour let fall between finger and thumb, the sikku, looping round every dot without touching one. The rice feeds the ants and the birds, and a yellow pumpkin flower goes in the middle.",
      window: [0.21, 0.23, 0.3, 0.33],
      side: "right",
    },
    {
      tithi: "Thai 1 · sunrise",
      title: "Thai Pongal",
      native: "தைப்பொங்கல்",
      body: "Out in the open, facing east: a new clay pot on a hearth of three stones, a turmeric plant tied round its neck and sugarcane stood over it. When the milk rises and boils over the rim, the women call the kulavai and everyone shouts “Pongalo Pongal!”, for pongal means to boil over, and a house that overflows will have plenty. Then in go the new rice, jaggery, ghee and cardamom.",
      window: [0.34, 0.36, 0.45, 0.48],
      side: "left",
    },
    {
      tithi: "Thai 1 · the morning",
      title: "For Surya",
      native: "சூரிய வழிபாடு",
      body: "The first of it is for the sun, who ripened the crop. The padaiyal is laid on a banana leaf before the pot: sakkarai pongal, sugarcane, bananas, a coconut broken open and a bunch of turmeric, with the brass kuthuvilakku lit beside it. Camphor is shown to Surya, and only then does the house eat.",
      window: [0.49, 0.51, 0.58, 0.61],
      side: "right",
    },
    {
      tithi: "Thai 2 · for the cattle",
      title: "Mattu Pongal",
      native: "மாட்டுப் பொங்கல்",
      body: "The next day is for the cattle who pulled the plough. They are bathed, their horns scraped and painted and capped with brass, and they are garlanded, hung with bells, marked with turmeric and kumkum, and fed pongal before anyone else. In the villages round Madurai these are also the days of jallikattu, when young men try to hold on to the hump of a running bull.",
      window: [0.62, 0.64, 0.71, 0.74],
      side: "left",
    },
    {
      tithi: "Thai 3 · the day for visiting",
      title: "Kaanum Pongal",
      native: "காணும் பொங்கல்",
      body: "Kaanum means to see. Families carry food from home to the riverbank and the beach, and the young bow to touch their elders' feet and are blessed. In the morning sisters set out kanu pidi, little balls of coloured rice on a turmeric leaf, for the crows, and pray for their brothers.",
      window: [0.75, 0.77, 0.84, 0.87],
      side: "right",
    },
  ],
  finale: {
    native: "தை பிறந்தால் வழி பிறக்கும்",
    english: "when Thai is born, a way is born",
    window: [0.9, 0.92, 0.975, 0.998],
  },
  hints: {
    scroll: "scroll to light the Bhogi fire",
    touch: [
      {
        text: "touch between the dots to twist the line",
        window: [0.25, 0.27, 0.32, 0.34],
      },
      {
        text: "hold the fire to bring the pot to the boil",
        window: [0.36, 0.38, 0.43, 0.45],
      },
      {
        text: "touch the cattle to ring their bells",
        window: [0.63, 0.65, 0.72, 0.74],
      },
    ],
  },
  verse: {
    lines: ["சுழன்றும்ஏர்ப் பின்னது உலகம் அதனால்", "உழந்தும் உழவே தலை."],
    lang: "ta",
    script: "tamil",
    english:
      "However it turns, the world follows the plough; so, for all its toil, farming comes first.",
    source: "Thirukkural 1031 · Uzhavu, on farming",
  },
  card: { native: "இனிய பொங்கல் நல்வாழ்த்துகள்", english: "Happy Pongal" },
  returnLink: "back to the Bhogi fire",
  soundLabel:
    "nadaswaram and thavil in raga Mohanam, veena, parai, the Bhogi fire, the pot boiling over, and cattle bells",
  about: {
    name: "Thai Pongal",
    alternateName: [
      "Pongal",
      "பொங்கல்",
      "தைப்பொங்கல்",
      "Pongal festival",
      "Tamil harvest festival",
    ],
    sameAs: "https://en.wikipedia.org/wiki/Pongal_(festival)",
  },
  ink: "#0a0605",
};
