import type { JourneyContent } from "../types";

export const onam: JourneyContent = {
  id: "onam",
  path: "/onam",
  name: "Ōṇam",
  festival: "Onam",
  native: "ഓണം",
  lang: "ml",
  script: "malayalam",
  tagline: "the king comes home",
  greeting: "ഓണാശംസകൾ",
  pageTitle: "Ōṇam — the king comes home",
  description:
    "Scroll through Onam in Kerala: Mahabali's story in shadows on a lamp-lit screen, a pookalam that grows a ring each morning from Atham to Thiruvonam, the sadya on a banana leaf, the clapping circle of Thiruvathira, the painted tigers of Thrissur and the snake boats of Aranmula.",
  share: "Ten mornings of flowers, a feast on a leaf and a hundred oars, for the king who comes home.",
  keywords: [
    "Onam",
    "ഓണം",
    "Thiruvonam",
    "Chingam",
    "Mahabali",
    "Maveli",
    "Vamana",
    "Atham",
    "Pookalam",
    "Athapookalam",
    "Thrikkakara Appan",
    "Onathappan",
    "Onasadya",
    "Sadya",
    "Kaanam vittum Onam unnanam",
    "Thiruvathira kali",
    "Kaikottikali",
    "kasavu",
    "nilavilakku",
    "Pulikali",
    "Thrissur",
    "Vallam kali",
    "Aranmula",
    "Chundan vallam",
    "Palliyodam",
    "Vanchipattu",
    "Chenda melam",
    "Panchari melam",
    "Kerala",
  ],
  length: 1200,
  hero: [0, 0, 0.035, 0.06],
  chapters: [
    {
      tithi: "Chingam · the old story",
      title: "Mahabali",
      native: "മഹാബലി",
      body: "Mahabali, an asura king, ruled this land so justly that everyone was equal. Vishnu came to him as Vamana, a boy priest, and asked for three steps of land. He grew until two steps held the earth and the sky, and Mahabali bowed his head for the third and was pressed down into Patala. He asked one thing: to visit his people once a year.",
      window: [0.065, 0.08, 0.15, 0.172],
      side: "right",
    },
    {
      tithi: "Atham to Thiruvonam · ten mornings",
      title: "Pookalam",
      native: "പൂക്കളം",
      body: "From Atham, ten days out, a pookalam is laid in the swept mittam to welcome him. The first morning it is a small round of white thumba; each day adds a ring and a flower: red chethi, marigold, hibiscus, blue shankhupushpam. On Thiruvonam the Thrikkakara Appan, clay pyramids for the Vamana of Thrikkakara, are set at its heart.",
      window: [0.188, 0.203, 0.29, 0.312],
      side: "left",
    },
    {
      tithi: "Thiruvonam · noon",
      title: "Onasadya",
      native: "ഓണസദ്യ",
      body: "On a banana leaf, its tip to the left, every dish has its place: chips, sharkara varatti and pickles at the top left, then pachadi, thoran, avial, olan and kalan; pappadam and banana below; rice in the middle with parippu and sambar, and payasam last. Kaanam vittum Onam unnanam: sell even your land, but eat the Onam feast.",
      window: [0.328, 0.343, 0.42, 0.442],
      side: "right",
    },
    {
      tithi: "Onam · the evening",
      title: "Thiruvathira kali",
      native: "തിരുവാതിരക്കളി",
      body: "At dusk the women come out in kasavu, cream cotton with a border of gold, jasmine in their hair. They dance in a slow circle round the nilavilakku, the tall brass lamp, one singing each line and the rest answering it, stepping and clapping: kaikottikali, the clapping dance.",
      window: [0.458, 0.473, 0.545, 0.567],
      side: "left",
    },
    {
      tithi: "Naalaam Onam · Thrissur",
      title: "Pulikali",
      native: "പുലിക്കളി",
      body: "On the fourth day of Onam the streets of Thrissur fill with tigers: men painted for hours since before dawn in yellow and black, each great belly painted as a tiger's face. They prowl and pounce round Swaraj Round to the chenda, thakil and udukku, and shake their bellies at the crowd.",
      window: [0.583, 0.598, 0.665, 0.687],
      side: "right",
    },
    {
      tithi: "Uthrattathi · Aranmula, on the Pamba",
      title: "Vallam kali",
      native: "വള്ളംകളി",
      body: "The chundan vallam, a snake boat over a hundred feet long, its stern raised like a cobra's hood. Two to a row, a hundred and more rowers in white mundu pull as one to the vanchipattu, the boat song: the singers call and the oars answer. At Aranmula the palliyodams of the river's villages row to the Parthasarathy temple, and the banks sing with them.",
      window: [0.705, 0.72, 0.795, 0.817],
      side: "left",
    },
    {
      tithi: "The last evening",
      title: "Maveli goes back",
      native: "മാവേലി മടങ്ങുന്നു",
      body: "The flowers wilt, the lamp burns low, and Maveli goes back under his palm-leaf umbrella, glad that his people are well. Next Chingam the thumba will flower again, and he will come home.",
      window: [0.858, 0.87, 0.915, 0.93],
      side: "right",
    },
  ],
  finale: { native: "ഓണാശംസകൾ", english: "until Maveli comes again", window: [0.94, 0.952, 0.985, 0.999] },
  hints: {
    scroll: "scroll to light the lamps behind the screen",
    touch: [
      { text: "touch the pookalam to add flowers", window: [0.21, 0.225, 0.3, 0.315] },
      { text: "touch a tiger to shake its belly", window: [0.6, 0.615, 0.675, 0.69] },
      { text: "touch the river to row faster", window: [0.722, 0.737, 0.83, 0.845] },
    ],
  },
  verse: {
    lines: [
      "മാവേലി നാടു വാണീടും കാലം,",
      "മാനുഷരെല്ലാരുമൊന്നുപോലെ.",
      "ആമോദത്തോടെ വസിക്കും കാലം,",
      "ആപത്തങ്ങാർക്കുമൊട്ടില്ല താനും.",
      "കള്ളവുമില്ല ചതിയുമില്ല,",
      "എള്ളോളമില്ല പൊളിവചനം.",
    ],
    lang: "ml",
    script: "malayalam",
    english:
      "When Maveli ruled the land, all people were as one. They lived in joy, and no harm came to anyone. There was no theft and no deceit, and not a sesame seed's worth of lies.",
    source: "Onappattu · a traditional Malayalam folk song of Onam",
  },
  card: { native: "ഓണാശംസകൾ", english: "Happy Onam" },
  returnLink: "back to the shadow screen",
  soundLabel: "the edakka, a veena, kuzhal and kombu, vanchipattu boat songs, clapping, thakil and udukku, and a chenda melam",
  about: {
    name: "Onam",
    alternateName: ["ഓണം", "Thiruvonam", "Thiruonam", "Onam festival"],
    sameAs: "https://en.wikipedia.org/wiki/Onam",
  },
  ink: "#070506",
};
