import type { JourneyContent } from "../types";

export const sankranti: JourneyContent = {
  id: "sankranti",
  path: "/makar-sankranti",
  name: "Makar Saṅkrānti",
  festival: "Makar Sankranti",
  native: "मकर संक्रांति",
  lang: "hi",
  script: "deva",
  tagline: "the sun turns north",
  greeting: "शुभ संक्रांति",
  pageTitle: "Makar Saṅkrānti — the sun turns north",
  description:
    "Scroll through one winter day across India, following the sun west: the dawn dip at the Sangam in Prayagraj, dahi-chura and khichdi in Bihar, tilgul and black saris in Maharashtra, and the kites of Uttarayan over the rooftops of Ahmedabad until the tukkal lanterns rise at night.",
  share: "One winter day across India, from the dawn dip at the Sangam to the kites over Ahmedabad.",
  keywords: [
    "Makar Sankranti",
    "मकर संक्रांति",
    "Uttarayan",
    "Uttarayana",
    "Sankranti",
    "Khichdi",
    "Magh Mela",
    "Sangam",
    "Prayagraj",
    "dahi chura",
    "tilkut",
    "tilgul",
    "haldi kunku",
    "sugad",
    "patang",
    "manja",
    "firki",
    "kai po che",
    "tukkal",
    "undhiyu",
    "chikki",
    "Ahmedabad",
    "kite festival",
  ],
  length: 1200,
  hero: [0, 0, 0.035, 0.06],
  chapters: [
    {
      tithi: "Prayagraj · first light",
      title: "Sangam snan",
      native: "संगम स्नान",
      body: "Where the Ganga, the Yamuna and the unseen Saraswati meet, the tents of the Magh Mela cover the sands, and pilgrims wade into the January water before sunrise. Three dips, and then arghya: water poured from a copper lota to Surya as he comes up. On the bank the sadhus keep their dhuni fires burning.",
      window: [0.065, 0.085, 0.145, 0.17],
      side: "right",
    },
    {
      tithi: "Bihar and Uttar Pradesh · the morning sun",
      title: "Dahi-chura",
      native: "दही-चूड़ा, खिचड़ी",
      body: "Breakfast out in the dhoop: chura, beaten rice, with thick dahi and a lump of gur, and tilkut, sesame pounded into jaggery. By night there is khichdi of new rice and urad dal, with its “four friends”: dahi, papad, ghee and achaar. In UP the day is simply called Khichdi. It is Pongal in Tamil Nadu, Magh Bihu in Assam, and Lohri in Punjab the night before.",
      window: [0.2, 0.215, 0.275, 0.3],
      side: "left",
    },
    {
      tithi: "Maharashtra · the afternoon",
      title: "Tilgul",
      native: "तिळगूळ घ्या, गोड गोड बोला",
      body: "“Tilgul ghya, goḍ goḍ bola”: take sesame and jaggery, and speak sweetly. Women wear black, the one day of the year for it, since black holds the winter sun, and a new bride wears jewellery of sugared sesame. At haldi-kunku they touch turmeric and kumkum to each other's foreheads and give vaan from the sugad, little clay pots of carrots, ber and sugarcane.",
      window: [0.325, 0.34, 0.4, 0.425],
      side: "right",
    },
    {
      tithi: "Ahmedabad · Uttarayan",
      title: "Patang",
      native: "पतंग",
      body: "In the pols of the old city, lanes of carved wooden houses, every terrace is taken by morning. Up come the patang, paper kites on bamboo, and the firki, reels of manja: cotton string coated with rice glue and powdered glass. Someone brings undhiyu, winter vegetables once slow-cooked upside down in a buried clay pot, and chikki of peanuts and gur.",
      window: [0.455, 0.47, 0.53, 0.555],
      side: "left",
    },
    {
      tithi: "Uttarayan · the afternoon",
      title: "Kai po che!",
      native: "काई पो छे!",
      body: "Two strings cross and the pech begins: one flyer lets the string run, the other pulls it in, glass sawing on glass, until one gives. The cut kite drifts off loose, children run across the roofs for it with long poles, and the whole terrace shouts “kai po che!”, I've cut it!",
      window: [0.565, 0.58, 0.645, 0.67],
      side: "right",
    },
    {
      tithi: "Makara · sunset",
      title: "Uttarayan",
      native: "उत्तरायण",
      body: "Today the sun crossed into Makara, Capricorn, and turned north for six months. Unlike almost every other festival it follows the sun, not the moon, so it falls on the same date nearly every year: 14 January. It is said Surya visits his son Shani, lord of Makara, and they make peace; and Bhishma, on his bed of arrows, waited for this turning before he let himself die.",
      window: [0.68, 0.695, 0.755, 0.78],
      side: "left",
    },
    {
      tithi: "Uttarayan · the night",
      title: "Tukkal",
      native: "तुक्कल",
      body: "After dark the kites become lights. Tukkal, paper lanterns with a small flame inside, are tied one above another on a kite string and let up from the roofs, until the sky over the old city fills with slow red stars. There are fireworks over the terraces, and nobody goes down until late.",
      window: [0.795, 0.81, 0.87, 0.895],
      side: "right",
    },
  ],
  finale: { native: "शुभ मकर संक्रांति", english: "the sun turns north, and the days grow long", window: [0.91, 0.93, 0.975, 0.998] },
  hints: {
    scroll: "scroll to the river before dawn",
    touch: [
      { text: "touch the river to offer arghya", window: [0.09, 0.105, 0.15, 0.165] },
      { text: "drag to fly your kite", window: [0.465, 0.48, 0.545, 0.56] },
      { text: "cross another string to cut its kite", window: [0.58, 0.595, 0.77, 0.785] },
      { text: "touch the dark to send up a tukkal", window: [0.81, 0.825, 0.9, 0.915] },
    ],
  },
  verse: {
    lines: ["चित्रं देवानामुदगादनीकं", "चक्षुर्मित्रस्य वरुणस्याग्नेः ।", "आप्रा द्यावापृथिवी अन्तरिक्षं", "सूर्य आत्मा जगतस्तस्थुषश्च ॥"],
    lang: "sa",
    english:
      "The bright face of the gods has risen, the eye of Mitra, Varuṇa and Agni. He has filled the sky, the earth and the air between: Sūrya, the soul of all that moves and all that stands still.",
    source: "Ṛgveda 1.115.1",
  },
  card: { native: "मकर संक्रांति की शुभकामनाएँ", english: "Happy Makar Sankranti" },
  returnLink: "back to the river at dawn",
  soundLabel: "shehnai and tanpura at dawn, bansuri, dholki, dhol and a brass band on the rooftops, and bells for the lanterns",
  about: {
    name: "Makar Sankranti",
    alternateName: ["Makara Sankranti", "मकर संक्रांति", "Uttarayan", "Uttarayana", "Khichdi", "Sankranti"],
    sameAs: "https://en.wikipedia.org/wiki/Makar_Sankranti",
  },
  ink: "#060812",
};
