import type { JourneyContent } from "../types";

export const navratri: JourneyContent = {
  id: "navratri",
  path: "/navratri",
  name: "Navarātri",
  festival: "Navratri",
  native: "નવરાત્રી",
  lang: "gu",
  script: "gujarati",
  tagline: "nine nights round the garbo",
  greeting: "જય અંબે",
  pageTitle: "Navarātri — nine nights round the garbo",
  description:
    "Scroll through Navratri in a Gujarat pol: the kalash and the barley sown on the first morning, the garbo lamp carried to the chowk, nine lamps for the nine forms of the goddess, garba and dandiya raas till past midnight, and Ravana burning on Dussehra.",
  share: "Nine nights round the garbo, from the first lamp to Ravana in flames.",
  keywords: [
    "Navratri",
    "Navaratri",
    "નવરાત્રી",
    "Garba",
    "Dandiya Raas",
    "garbo",
    "Ghatasthapana",
    "jawara",
    "akhand jyot",
    "mandvi",
    "Amba",
    "Mata ni Pachedi",
    "Navadurga",
    "chaniya choli",
    "kediyu",
    "Dussehra",
    "Vijayadashami",
    "Ravana Dahan",
    "Shami puja",
    "Gujarat",
  ],
  length: 1150,
  hero: [0, 0, 0.04, 0.07],
  chapters: [
    {
      tithi: "Ashvin Shukla Pratipada · morning",
      title: "Ghatasthapana",
      native: "ઘટસ્થાપના",
      body: "On the first morning soil is spread at the mandvi and barley sown in it, the jawara. On it stands the ghat, a kalash of water under mango leaves and a coconut in red cloth, and beside it the akhand jyot, a ghee lamp that must not go out for nine days.",
      window: [0.08, 0.1, 0.17, 0.2],
      side: "left",
    },
    {
      tithi: "Pratipada · dusk",
      title: "The garbo",
      native: "ગરબો",
      body: "A clay pot pierced all over, with a lamp burning inside: the garbo, from garbha, the womb, the light of life held within the goddess. The women carry it on their heads to the chowk and set it in the mandvi, before Amba on a painted Mata ni Pachedi.",
      window: [0.21, 0.23, 0.3, 0.33],
      side: "right",
    },
    {
      tithi: "Pratipada to Navami · nine nights",
      title: "Navadurga",
      native: "નવદુર્ગા",
      body: "One form of the goddess for each night, from Shailaputri, daughter of the mountain, to Siddhidatri, who grants every power, and one more lantern lit over the chowk each night. On Ashtami little girls are seated on the otla and fed puri, chana and sheero as the goddess herself: the kanya pujan.",
      window: [0.34, 0.36, 0.43, 0.46],
      side: "left",
    },
    {
      tithi: "every night · till late",
      title: "Garba",
      native: "ગરબા",
      body: "The women begin, slowly, in chaniya choli heavy with mirror work: three claps and a turn, round and round the garbo. Then the men in kediyu, then everyone. The circle grows ring inside ring, as life turns round the one still point, the goddess at its centre.",
      window: [0.47, 0.49, 0.57, 0.6],
      side: "right",
    },
    {
      tithi: "Ashtami and Navami · past midnight",
      title: "Dandiya Raas",
      native: "દાંડિયા રાસ",
      body: "Two rings facing each other and a painted stick in every hand, struck together, then across, then on to the next partner. It is the raas Krishna danced with the gopis in Vrindavan, and the dhol plays it faster and faster on the last nights.",
      window: [0.61, 0.63, 0.7, 0.73],
      side: "left",
    },
    {
      tithi: "Vijayadashami · dusk",
      title: "Dussehra",
      native: "દશેરા",
      body: "On the tenth day Ram's arrow finds Ravana, and in the maidan the ten-headed effigy, packed with crackers, goes up in flames. The shami tree is worshipped, where the Pandavas hid their weapons, and that morning all Gujarat eats fafda and jalebi.",
      window: [0.74, 0.76, 0.83, 0.86],
      side: "right",
    },
  ],
  finale: {
    native: "જય માતાજી",
    english: "till the garbo is lit again",
    window: [0.9, 0.92, 0.975, 0.998],
  },
  hints: {
    scroll: "scroll to sow the jawara",
    touch: [
      {
        text: "touch the next lamp to light it",
        window: [0.36, 0.38, 0.45, 0.47],
      },
      {
        text: "tap the chowk to join the garba",
        window: [0.5, 0.52, 0.59, 0.61],
      },
      { text: "tap to strike the dandiya", window: [0.63, 0.65, 0.71, 0.73] },
      {
        text: "touch Ravana to loose Ram's arrow",
        window: [0.772, 0.781, 0.8, 0.806],
      },
    ],
  },
  verse: {
    lines: ["या देवी सर्वभूतेषु शक्तिरूपेण संस्थिता ।", "नमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः ॥"],
    lang: "sa",
    script: "deva",
    english: "To the goddess who dwells in every being as power: we bow to her, we bow to her, we bow to her, again and again.",
    source: "Devī Māhātmya 5 · Mārkaṇḍeya Purāṇa",
  },
  card: { native: "શુભ નવરાત્રી", english: "Shubh Navratri" },
  returnLink: "back to the first lamp",
  soundLabel: "dhol, harmonium, shehnai, manjira, hand claps, dandiya, the shankh and crackers",
  about: {
    name: "Navratri",
    alternateName: ["Navaratri", "નવરાત્રી", "Garba", "Navratri in Gujarat"],
    sameAs: "https://en.wikipedia.org/wiki/Navaratri",
  },
  ink: "#070308",
};
