import type { JourneyContent } from "../types";

export const holi: JourneyContent = {
  id: "holi",
  path: "/holi",
  name: "Holī",
  festival: "Holi",
  native: "होली",
  lang: "hi",
  tagline: "the fire and the colour",
  greeting: "होली है!",
  pageTitle: "Holī — the fire and the colour",
  description:
    "Scroll through Holi: Holika's fire under the Phalgun full moon, the first colour on a grandmother's feet, Krishna and Radha in Braj, a whole lane drenched in gulal, thandai and gujiya, and the palash in flower at dusk.",
  share: "From Holika's fire under the full moon to a whole lane drenched in colour.",
  keywords: [
    "Holi",
    "होली",
    "Holika Dahan",
    "Prahlad",
    "Phalgun Purnima",
    "Dhulandi",
    "Rangwali Holi",
    "gulal",
    "pichkari",
    "Braj",
    "Lathmar Holi",
    "Barsana",
    "Phoolon ki Holi",
    "Vrindavan",
    "thandai",
    "gujiya",
    "palash",
    "tesu",
    "bura na mano Holi hai",
  ],
  length: 1080,
  hero: [0, 0, 0.04, 0.07],
  chapters: [
    {
      tithi: "Phalgun Purnima · the night",
      title: "Holika Dahan",
      native: "होलिका दहन",
      body: "Wood and cow-dung cakes piled in the square under the full moon. Holika sat in the fire with Prahlad in her lap; she burned, and he walked out saying Narayan's name. So the town walks round it, with new wheat and a coconut for the flames.",
      window: [0.08, 0.1, 0.17, 0.2],
      side: "right",
    },
    {
      tithi: "Dhulandi · the morning after",
      title: "The first colour",
      native: "पहला रंग",
      body: "Gulal in a brass plate, heaped pink and green and yellow. Before anyone else, a pinch on the feet of the eldest in the house, and her blessing, and then a streak across her cheek.",
      window: [0.21, 0.23, 0.3, 0.33],
      side: "left",
    },
    {
      tithi: "Braj · Barsana and Vrindavan",
      title: "Krishna and Radha",
      native: "राधा कृष्ण",
      body: "Dark little Krishna asked Yashoda why Radha was so fair, and she told him to go and colour her face. In Barsana the women still meet the men of Nandgaon with lathis, and in Vrindavan the priests shower flowers.",
      window: [0.34, 0.36, 0.43, 0.46],
      side: "right",
    },
    {
      tithi: "Rangwali Holi · noon",
      title: "Holi hai!",
      native: "होली है!",
      body: "Then the whole lane: dhol, pichkaris, buckets from the balconies, gulal thrown until the air itself is pink. No one is a stranger, and no one stays clean.",
      window: [0.47, 0.49, 0.57, 0.6],
      side: "left",
    },
    {
      tithi: "The afternoon",
      title: "Thandai and gujiya",
      native: "ठंडाई और गुजिया",
      body: "Thandai, cold milk with almonds, fennel, pepper and rose ground into it, and gujiya from every kitchen on the lane. Old quarrels end in an embrace: bura na mano, Holi hai.",
      window: [0.61, 0.63, 0.7, 0.73],
      side: "right",
    },
    {
      tithi: "Vasant · the evening",
      title: "Palash in flower",
      native: "टेसू के फूल",
      body: "Washed, in new clothes, out visiting. The lane keeps its colour, and at its end the palash is in flower: tesu, whose petals, soaked overnight, coloured Holi long before gulal came in packets.",
      window: [0.74, 0.76, 0.83, 0.86],
      side: "left",
    },
  ],
  finale: { native: "बुरा न मानो, होली है", english: "don't mind, it's Holi", window: [0.9, 0.92, 0.975, 0.998] },
  hints: {
    scroll: "scroll to light the fire",
    touch: [
      { text: "touch the fire", window: [0.1, 0.12, 0.18, 0.2] },
      { text: "touch to throw gulal", window: [0.26, 0.28, 0.44, 0.46] },
      { text: "drag to throw gulal", window: [0.49, 0.51, 0.58, 0.6] },
      { text: "touch the palash", window: [0.77, 0.79, 0.86, 0.88] },
    ],
  },
  verse: {
    lines: ["फागुन के दिन चार,", "होली खेल मना रे ।", "उड़त गुलाल लाल भयो अंबर,", "बरसत रंग अपार रे ॥"],
    lang: "hi",
    english: "Phagun lasts four days: play Holi, my heart. The gulal flies and the sky turns red, and colour rains without end.",
    source: "Mīrābāī, a Holi pad",
  },
  card: { native: "होली की शुभकामनाएँ", english: "Happy Holi" },
  returnLink: "back to the fire",
  soundLabel: "dhol, dholak, manjira, bansuri in Raag Kafi, and a crowd",
  about: {
    name: "Holi",
    alternateName: ["होली", "Holika Dahan", "Dhulandi", "Rangwali Holi", "Festival of Colours"],
    sameAs: "https://en.wikipedia.org/wiki/Holi",
  },
  ink: "#0a0508",
};
