import type { JourneyContent } from "../types";

export const diwali: JourneyContent = {
  id: "diwali",
  path: "/diwali",
  name: "Deepāvalī",
  festival: "Diwali",
  native: "दीपावली",
  lang: "hi",
  tagline: "a row of lamps",
  greeting: "शुभ दीपावली",
  pageTitle: "Deepāvalī — a row of lamps",
  description:
    "Scroll through the five days of Diwali: one lamp for Yama at the door, a rangoli for Lakshmi, a whole town lit for Ram coming home, and the sky on the darkest night of the year.",
  share: "From one lamp at the door to a whole town lit for Ram coming home.",
  keywords: [
    "Diwali",
    "Deepavali",
    "दीपावली",
    "Dhanteras",
    "Yama Deepam",
    "Naraka Chaturdashi",
    "Choti Diwali",
    "Rangoli",
    "Lakshmi Puja",
    "Ayodhya",
    "Deepotsav",
    "diya",
    "akash kandil",
    "phuljhadi",
    "Amavasya",
  ],
  length: 1100,
  hero: [0, 0, 0.04, 0.07],
  chapters: [
    {
      tithi: "Dhanteras · Trayodashi",
      title: "Yama Deepam",
      native: "यम दीपम्",
      body: "The first lamp is lit on the thirteenth night and set at the door facing south, for Yama, so that death passes the house by.",
      window: [0.08, 0.1, 0.17, 0.2],
      side: "right",
    },
    {
      tithi: "Choti Diwali · Chaturdashi",
      title: "Naraka Chaturdashi",
      native: "नरक चतुर्दशी",
      body: "Before dawn, oil and ubtan and a bath, for the morning Krishna and Satyabhama rid the world of Narakasura. Fourteen lamps along the step, one for each of the worlds.",
      window: [0.21, 0.23, 0.3, 0.33],
      side: "left",
    },
    {
      tithi: "Amavasya · the afternoon",
      title: "Rangoli",
      native: "रंगोली",
      body: "Rice flour and colour poured between finger and thumb, a pattern at the door so that she can find the way in.",
      window: [0.34, 0.36, 0.43, 0.46],
      side: "right",
    },
    {
      tithi: "Amavasya · the darkest night",
      title: "Lakshmi Puja",
      native: "लक्ष्मी पूजा",
      body: "Small red footprints drawn walking in from the door, and every lamp in the house lit, so that Lakshmi comes in and stays.",
      window: [0.47, 0.49, 0.57, 0.6],
      side: "left",
    },
    {
      tithi: "Amavasya · the whole town",
      title: "Ram comes home",
      native: "राम का आगमन",
      body: "Fourteen years in the forest, and Ayodhya lit every lamp it had to show him the way home. Every town has done the same since.",
      window: [0.61, 0.63, 0.7, 0.73],
      side: "right",
    },
    {
      tithi: "Amavasya · midnight",
      title: "Phuljhaṛī",
      native: "फुलझड़ी",
      body: "Sparklers in children's hands, the anar's fountain in the street, and for one night the sky as bright as the ground.",
      window: [0.74, 0.76, 0.83, 0.86],
      side: "left",
    },
  ],
  finale: { native: "शुभ दीपावली", english: "may the light stay", window: [0.9, 0.92, 0.975, 0.998] },
  hints: {
    scroll: "scroll to light the first lamp",
    touch: [
      { text: "touch the floor to pour colour", window: [0.37, 0.39, 0.44, 0.46] },
      { text: "touch a lamp to light it", window: [0.5, 0.52, 0.58, 0.6] },
      { text: "touch the sky", window: [0.76, 0.78, 0.86, 0.88] },
    ],
  },
  verse: {
    lines: ["असतो मा सद्गमय ।", "तमसो मा ज्योतिर्गमय ।", "मृत्योर्मा अमृतं गमय ॥"],
    lang: "sa",
    english: "Lead me from the unreal to the real, from darkness to light, from death to the deathless.",
    source: "Bṛhadāraṇyaka Upaniṣad 1.3.28",
  },
  card: { native: "शुभ दीपावली", english: "Shubh Deepavali" },
  returnLink: "back to the first lamp",
  soundLabel: "bansuri, tanpura, temple bells, dholak and crackers",
  about: {
    name: "Diwali",
    alternateName: ["Deepavali", "दीपावली", "Deepawali"],
    sameAs: "https://en.wikipedia.org/wiki/Diwali",
  },
  ink: "#06040a",
};
